config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations'}

  root 'pins#index'

  get 'u/:username' => 'users#show', as: :profile
  resources :users

  resources :pins, path: 'p' do
    member do
      put 'like', to: 'pins#upvote'
    end
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user

  acts_as_votable
  acts_as_taggable_on :tags, :aditional_tags

  #TODO Add image source field

  has_attached_file :image, processors: [:thumbnail, :paperclip_optimizer]
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter
  gravtastic :default => 'identicon'

  has_many :pins, :dependent => :delete_all
  has_one :profile, :dependent => :delete
  before_create :build_profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # Finds a pin using a ID only on the specified methods
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]

  # Redirects the user back if they are not the owner
  before_action :user_is_owner, only: [:edit, :destroy]

  # Make sure a user is signed in before he can do stuff with the pins
  before_action :authenticate_user!, except: [:index, :show]

  # Index action
  def index
    @pins = Pin.all.order('created_at DESC')
  end

  # Show action
  def show
    # Imported automatically via before_action
  end

  # New action
  def new
    @pin = current_user.pins.build
  end


  # Create action
  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Successfully created new Pin!'
    else
      render 'new'
    end
  end

  # Edit action
  def edit

  end

  # Helper method for if an pin is updated
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated'
    else
      render 'edit'
    end
  end

  # Destroys a pin
  def destroy
    @pin.destroy
    redirect_to root_path
  end

  #TODO Change this to an AJAX call
  def upvote
    if current_user.voted_for? @pin
      @pin.unliked_by current_user
    else
      @pin.liked_by current_user
    end

    redirect_to :back
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image, :tag_list, :aditional_tag_list)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

  def user_is_owner
    if current_user.email != @pin.user.email
      #TODO Implement custom notices
      redirect_to root_path, notice: "You don't have access to this resource!"
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def show
    # Getting the user via the :find_user method
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end

  def find_user
    @user = User.find_by username: params[:username]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def render_flash
    render 'flash' if can_flash?
  end

  def can_flash?
    flash.keys.sort == [:from, :object_id, :object_type, :type]
  end

  def flash_object
    flash[:object_type].classify.constantize.where(id: flash[:object_id]).first
  end

  def flash_path
    # EX: pins/flash/create/_success.html.haml
    File.join(controller_name, 'flash', flash[:from].to_s, flash[:type].to_s)
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flash.html.haml
.alert.alert-info
  .container

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= (yield(:title) + ' :: ' unless yield(:title).blank?).to_s + ' Makichan - Anime pinboard'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = disqus_init
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to 'Makichan', root_path

        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'New pin', new_pin_path
            %li.dropdown
              %a(class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-expanded="false")
                Welcome,
                = current_user.username
              %ul(class="dropdown-menu" role="menu")
                %li= link_to 'Profile', profile_path(username: current_user.username)
                %li.divider
                %li= link_to 'Account settings', edit_user_registration_path
                %li= link_to 'Sign out', destroy_user_session_path, class: 'text-danger', method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Sign Up', new_user_registration_path
            %li= link_to 'Sign In', new_user_session_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: 'alert alert-info' do
          = msg
          %button(type="button" class="close" data-dismiss="alert" aria-label="Close")
            %span(aria-hidden="true")
              &times;

      -#Content from
      = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true} do |f|
  - if @pin.errors.any?
    #errors
      %h2
        = pluralize(@pin.errors.count, 'error')
        prevented this pin from saving
        %ul
          - @pin.errors.full_messages.each do |msg|
            %li= msg

  = f.input :image, input_html: { class: 'form-control' }

  = f.input :tag_list, :input_html => { class: 'form-control', :data => { :role => 'tagsinput' } }

  = f.input :title, input_html: { class: 'form-control' }

  = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, class: 'btn btn-primary'

app/views/pins/edit.html.haml
= content_for(:title, "Edit pin #{@pin.title}")

.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Pin
      .panel-body
        %strong.center Current Image
        %br
        = image_tag @pin.image.url(:medium)
        = render 'form'

app/views/pins/index.html.haml
= content_for(:title, 'Home')

.container-fluid
  #pins.transitions-enabled
    - @pins.each do |pin|
      .box.panel.panel-default
        = link_to (image_tag asset_url(pin.image.url)), pin
        .panel-body
          %h2= link_to pin.title, pin
          %p.user
            Submitted by:
            %div.avatar
              = link_to (image_tag pin.user.gravatar_url), profile_path(username: pin.user.username)
            = link_to pin.user.username, profile_path(username: pin.user.username)

app/views/pins/new.html.haml
= content_for(:title, 'New Pin')

.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Pin
      .panel-body
        = render 'form'

app/views/pins/show.html.haml
= content_for(:title, " #{@pin.title}")
.row
  #pins-sidebar.center
    .col-md-4
      .panel-default
        .panel-heading
          .btn-group.pull-right
            - if user_signed_in?
              - if current_user.voted_for? @pin
                - @voted = true
            = link_to like_pin_path(@pin),
                method: :put, :class => 'btn btn-sm ' + (@voted ? 'btn-success' : 'btn-default') do
              %span.glyphicon.glyphicon-heart
                = @pin.get_likes.size

            - if user_signed_in? && current_user.email == @pin.user.email
              = link_to ' Edit Pin', edit_pin_path, class: 'btn btn-default btn-sm'
              = link_to 'Delete Pin', pin_path, method: :delete, data: { confirm: 'Are you sure?' },
                class: 'btn btn-danger btn-sm'

          %br
          %br
          %div(class="pins-info pull-right col-md- col-md-offset-5" style="margin-top: 15px; margin-botom: 15px;" )

            %b Uploaded on:
            %br
            = @pin.created_at.to_s(format = :short)

            %br
            %br

            %b Updated on:
            %br
            = @pin.updated_at.to_s(format = :short)


          %p.user
            Submitted by:
            %div.avatar
              = link_to (image_tag @pin.user.gravatar_url), @pin.user
            = link_to @pin.user.username, @pin.user

        .panel-footer
          .pin-liked-by
            - if @pin.get_likes.size != 0
              %b Liked by:
              - @pin.votes_for.voters.each do |user|
                = user.username
          %br
          - if @pin.image.url.nil? == false
            - file_size = number_to_human_size(@pin.image_file_size, precision: 2)
            = link_to "Download larger version (#{file_size.to_s} #{@pin.image_content_type.split('/').last.upcase})",
              asset_url(@pin.image.url), target: '_blank'

  #pins_show.center
    .col-md-8
      .panel-default
        .panel-heading.pin_image
          = image_tag asset_url(@pin.image.url), class: 'img-responsive'

        .panel-body
        %h1= @pin.title
        %p.description= @pin.description

        .panel-footer
          - disqus_thread

app/views/users/show.html.haml
= content_for :title, "#{@user.username}"
.row
  .col-md-12
    .panel-default
      .panel-heading
        %h1= @user.username

      .panel-body